/*******************************************************************************************************************
Name    :   PlatformCacheException
Purpose :   Custom exception class to handle errors specific to Platform Cache Utility operations.
====================================================================================================================
History                                                            
-------                                                            
VERSION     AUTHOR                  DATE                DETAIL                  
1.0         Sfdcchampsa           09/02/2024          INITIAL DEVELOPMENT     
********************************************************************************************************************/
public class PlatformCacheException extends Exception {
    // No additional properties or methods; serves as a marker exception
}